# Generated by Django 4.2.5 on 2023-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECU'), ('P', 'PROFORMA FACTURE'), ('I', 'FACTUR')], max_length=1),
        ),
    ]
